#!/usr/bin/env python3

import os
import rospkg
import rospy
from ros_model_generator.rossystem_generator import RosSystemModelGenerator
from rosgraph_monitor.observers.graph_observer import create_ros_graph_snapshot

r = rospkg.RosPack()

def generate_model_from_snapshot():
    file_path = os.path.join(r.get_path('rosgraph_monitor'), "resources/test.rossystem")
    components = create_ros_graph_snapshot()
    generator = RosSystemModelGenerator('demo')
    try:
        generator.dump_ros_system_model_list(components, file_path)
    except Exception as e:
        print(e.args)

if __name__ == "__main__":
    rospy.init_node('dummy_node')
    generate_model_from_snapshot()