#!/usr/bin/env python3

import os
import rospkg
import rospy
from ros_model_generator.rossystem_generator import RosSystemModelGenerator
from ros_model_generator.rosmodel_generator import RosModelGenerator
from rosgraph_monitor.observers.graph_observer import create_ros_graph_snapshot

r = rospkg.RosPack()

def generate_model_from_snapshot():
    rossystem_file = os.path.join(r.get_path('rosgraph_monitor'), "resources/test.rossystem")
    rosmodel_file = os.path.join(r.get_path('rosgraph_monitor'), "resources/test.ros")
    components = create_ros_graph_snapshot()
    print(components)
    rossystem_generator = RosSystemModelGenerator('demo')
    rosmodel_generator = RosModelGenerator()
    try:
        rossystem_generator.dump_ros_system_model_list(components, rossystem_file)
        rosmodel_generator.generate_ros_model_list(components, rosmodel_file)
    except Exception as e:
        print(e.args)

if __name__ == "__main__":
    rospy.init_node('rossystem_from_snapshot_generator')
    generate_model_from_snapshot()
